# -*- coding: utf-8 -*-
"""Twitter scrape and count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eE1WdQreTVOBvN48UEapnDrnqbnzQAZA
"""

import os
os.system('clear')
from datetime import date, datetime, timezone
import asyncio
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

! pip install twarc
from twarc import Twarc2

bearer_token = "AAAAAAAAAAAAAAAAAAAAANT3ewEAAAAA8vSq5XiVEMsT2wBLCkFJfkVh2oE%3Dt5BUEMTPeZAAF18MQGZLX6cFMV5ZbAYbDLi6qKbR7dSYvWLxNo" # replace the XXX with your bearer token
twarc_client = Twarc2(bearer_token=bearer_token)

# first, retrieving Tweets from May 26 to June 9, 2020
# (1) for all members
accounts = ["lisamurkowski", "SenDanSullivan", "SenDougJones", "SenShelby", "JohnBoozman", "SenTomCotton", "MarthaMcSallyAZ", "SenatorSinema", "SenFeinstein", "VP",
            "SenatorBennet", "SenCoryGardner", "SenBlumenthal", "ChrisMurphyCT", "SenatorCarper", "ChrisCoons", "marcorubio", "SenRickScott", "KLoeffler", "sendavidperdue",
            "maziehirono", "SenBrianSchatz", "SenJoniErnst", "ChuckGrassley", "MikeCrapo", "SenatorRisch", "SenDuckworth", "SenatorDurbin", "SenatorBraun", "SenToddYoung",
            "JerryMoran", "SenPatRoberts", "LeaderMcConnell", "RandPaul", "SenBillCassidy", "SenJohnKennedy", "SenMarkey", "SenWarren", "SenatorCardin", "ChrisVanHollen",
            "SenatorCollins", "SenAngusKing", "SenGaryPeters", "SenStabenow", "SenAmyKlobuchar", "SenTinaSmith", "RoyBlunt", "SenHawleyPress", "SenHydeSmith", "SenatorWicker",
            "SenatorTester", "SteveDaines", "SenatorBurr", "SenThomTillis", "SenKevinCramer", "SenJohnHoeven", "SenatorFischer", "SenSasse", "SenatorHassan", "SenatorShaheen",
            "SenBooker", "SenatorMenendez", "MartinHeinrich", "SenatorTomUdall", "SenCortezMasto", "SenJackyRosen", "gillibrandny", "SenSchumer", "SenSherrodBrown", "senrobportman",
            "JimInhofe", "SenatorLankford", "SenJeffMerkley", "RonWyden", "SenBobCasey", "SenToomey", "SenJackReed", "SenWhitehouse", "LindseyGrahamSC", "SenatorTimScott",
            "SenatorRounds", "SenJohnThune", "SenAlexander", "MarshaBlackburn", "JohnCornyn", "SenTedCruz", "SenMikeLee", "SenatorRomney", "timkaine", "MarkWarner",
            "SenatorLeahy", "SenSanders", "SenatorCantwell", "PattyMurray", "SenatorBaldwin", "SenRonJohnson", "SenCapito", "Sen_JoeManchin", "SenJohnBarrasso", "SenatorEnzi",
            "RepFinkenauer", "RepSpanberger", "RepKinzinger", "RepAdamSchiff", "RepAdamSmith", "RepAdrianSmith", "RepEspaillat", "RepAlGreen", "AlLawsonJr", "RepLowenthal",
            "AlbioSiresNJ", "RepAlexMooney", "RepAOC", "RepAdams", "RepAmata", "RepBera", "RepAndreCarson", "RepAndyBarr", "RepAndyBiggsAZ", "RepAndyHarrisMD",
            "RepAndyKimNJ", "RepAndyLevin", "RepAngieCraig", "RepKirkpatrick", "RepAnnieKuster", "RepAnnWagner", "RepAnnaEshoo", "RepBrindisi", "OAGMaryland", "repdelgado",
            "AustinScottGA08", "RepPressley", "RepBarbaraLee", "RepLoudermilk", "RepBenCline", "BenMcAdamsUT", "SenatorLujan", "BennieGThompson", "BettyMcCollum04", "RepBillFoster",
            "RepHuizenga", "RepBillJohnson", "USRepKeating", "BillPascrell", "CongBillPosey", "auctnr1", "RepBlaine", "boblatta", "BobbyLRush", "BobbyScott",
            "RepBonnie", "RepSchneider", "BradSherman", "RepBradWenstrup", "RepByrne", "RepLawrence", "CongBoyle", "RepGuthrie", "RepBrianBabin", "RepBrianFitz",
            "RepBrianHiggins", "RepBrianMast", "RepWesterman", "RepBryanSteil", "RepBuddyCarter", "RepCarolMiller", "RepMaloney", "CathyMcMorris", "RepRichmond", "CharlieCrist",
            "ChelliePingree", "RepCheri", "RepChipRoy", "RepChrisPappas", "RepChrisStewart", "RepHoulahan", "RepChuck", "Axne4Congress", "RepClayHiggins", "RepColinAllred",
            "ConorLambPA", "RepDanBishop", "RepDanCrenshaw", "RepDanKildee", "RepFredKeller", "RepGregMurphy", "RepLipinski", "RepMeuser", "RepNewhouse", "RepWebster", "RepDannyDavis", "RepLaHood", "RepDarrenSoto",
            "daveloebsack", "RepCicilline", "RepDaveJoyce", "RepDavidKustoff", "RepMcKinley", "RepDavidRouzer", "RepDavid", "RepDavidScott", "RepDavidTrone", "RepDeanPhillips",
            "RepDebHaaland", "RepDebDingell", "RepDLesko", "RepDMP", "RepDWStweets", "LtGovDennyHeck", "RepRiggleman", "RepDerekKilmer", "RepDevinNunes", "RepDianaDeGette",
            "RepDinaTitus", "RepDonBacon", "RepDonBeyer", "repdonyoung", "Donald_McEachin", "DonaldNorcross", "RepDonaldPayne", "DonnaShalala", "DorisMatsui", "RepDougCollins",
            "RepLaMalfa", "RepDLamborn", "RepDrewFerguson", "RepDustyJohnson", "Call_Me_Dutch", "RepDwightEvans", "repblumenauer", "RepEdCase", "RepPerlmutter", "RepEBJ",
            "ElaineLuriaVA", "EleanorNorton", "RepEliotEngel", "RepStefanik", "RepSlotkin", "repcleaver", "RepSwalwell", "RepFilemonVela", "RepRooney",
            "RepFrankLucas", "FrankPallone", "RepFredUpton", "RepWilson", "RepFrenchHill", "GKButterfield", "RepGarretGraves", "USRepGaryPalmer", "RepHolding", "GerryConnolly",
            "RepGilCisneros", "RepGrothman", "CongressmanGT", "RepGraceMeng", "gracenapolitano", "GregForMontana", "RepGregPence", "RepGregStanton", "RepGregSteube", "repgregwalden",
            "Kilili_Sablan", "RepGregoryMeeks", "RepGusBilirakis", "GReschenthaler", "RepGwenMoore", "RepJeffries", "RepHalRogers", "RepHaleyStevens", "RepHankJohnson", "RepHarley",
            "RepCuellar", "Ilhan", "RepJackBergman", "RepSpeier", "RepWalorski", "RepJahanaHayes", "HerreraBeutler", "JimLangevin", "RepRaskin",
            "janschakowsky", "RepGolden", "RepHuffman", "RepJasonCrow", "RepJasonSmith", "RepJeffDuncan", "JeffFortenberry", "RepWexton", "RepJenniffer", "RepJerryNadler",
            "RepMcNerney", "RepChuyGarcia", "RepJimBaird", "RepJimBanks", "RepJamesClyburn", "jimcoopertn", "RepJimCosta", "RepHagedorn", "jahimes", "Jim_Jordan",
            "RepMcGovern", "RepJimmyGomez", "RepJimmyPanetta", "JoaquinCastrotx", "RepArrington", "CongressmanHice", "RepJoeCourtney", "RepCunningham", "RepJoeNeguse", "RepJoeWilson",
            "RepJohnLarson", "JudgeCarter", "RepJohnCurtis", "RepGaramendi", "RepJohnJoyce", "RepJohnKatko", "repjohnlewis", "RepMoolenaar", "JohnRatcliffe", "RepJohnRose",
            "RepRutherfordFL", "RepSarbanes", "JohnYarmuth", "RepJoseSerrano", "RepJoeMorelle", "joekennedy", "RepJoshG", "RepJoshHarder", "RepBeatty", "RepJuanVargas",
            "RepJudyChu", "RepBrownley", "justinamash", "RepKarenBass", "WhipKClark", "RepKathleenRice", "USRepKCastor", "RepMikeGarcia", "RepKatiePorter", "RepKayGranger",
            "RepArmstrongND", "RepKenBuck", "KenCalvert", "HornForCongress", "RepKenMarchant", "RepKevinBrady", "repkevinhern", "kevinomccarthy", "RepKimSchrier", "RepSchrader",
            "LacyClayMO1", "Lancegooden", "RepLarryBucshon", "RepUnderwood", "leezeldin", "RepLindaSanchez", "RepLBR", "RepLizCheney", "RepFletcher", "RepLloydDoggett",
            "RepSmucker", "RepLoisFrankel", "RepLoriTrahan", "RepLouCorrea", "replouiegohmert", "RepRoybalAllard", "RepLucyMcBath", "MacTXPress", "RepDean", "RepVeasey",
            "RepMarciaFudge", "RepMarcyKaptur", "MarioDB", "MarkAmodeiNV2", "RepDeSaulnier", "RepMarkGreen", "RepMarkPocan", "RepMarkTakano", "RepMarkWalker", "SenMullin",
            "MarthaRobyAL", "RepMGS", "RepCartwright", "RepMattGaetz", "RepMaxRose", "RepMaxineWaters", "michaelcburgess", "RepCloudTX", "USRepMikeDoyle", "RepMichaelGuest",
            "RepMcCaul", "RepWaltzPress", "RepBost", "ConawayTX11", "RepGallagher", "RepMikeJohnson", "MikeKellyPA", "RepMikeLevin", "RepMikeQuigley",
            "RepMikeRogersAL", "CongMikeSimpson", "RepThompson", "RepMikeTurner", "RepSherrill", "RepMoBrooks", "RepMGriffith", "SpeakerPelosi", "RepBarragan", "DrNealDunnFL2",
            "NitaLowey", "NormaJTorres", "NydiaVelazquez", "PatrickMcHenry", "ColPaulCookRet", "RepGosar", "RepPaulMitchell", "RepPaulTonko", "RepPeteAguilar", "RepPeteOlson",
            "RepPeteStauber", "RepPeterDeFazio", "RepPeteKing", "PeterWelch", "DrPhilRoe", "RepJayapal", "CongressmanRaja", "RepAbraham", "RepRalphNorman", "TXRandy14",
            "RepRashida", "RepRaulRuizMD", "RepRaulGrijalva", "RepRichHudson", "RepRichardNeal", "RepRickCrawford", "RepRickLarsen", "RepRickAllen", "RepRoKhanna", "RobWittman",
            "RepRobWoodall", "Robert_Aderholt", "RepRobinKelly", "RodneyDavis", "RogerMarshallMD", "RepRWilliams", "RepRonEstes", "RepRonKind", "RepRonWright", "rosadelauro",
            "RepRossSpano", "RepRubenGallego", "RepRussFulcher", "RepCarbajal", "RepSamGraves", "SanfordBishop", "DesJarlaisTN04", "RepScottPerry", "RepScottPeters", "RepTipton",
            "RepCasten", "RepTiffany", "RepSeanMaloney", "sethmoulton", "RepDavids", "JacksonLeeTX18", "StaceyPlaskett", "RepStenyHoyer", "RepStephMurphy", "RepStephenLynch",
            "RepSteveChabot", "RepCohen", "SteveKingIA", "SteveScalise", "RepSteveStivers", "rep_stevewomack", "RepHorsford", "CongPalazzo", "SusanWBrooks", "RepSusanWild",
            "RepSusieLee", "RepDelBene", "RepBonamici", "RepSylviaGarcia", "SenTedBuddNC", "RepTedDeutch", "RepTedLieu", "RepTedYoho", "RepTerriSewell", "RepThomasMassie",
            "RepTomSuozzi", "RepTimBurchett", "RepTimRyan", "RepWalberg", "RepTjCox", "TomColeOK04", "GOPMajorityWhip", "RepTomGraves", "RepMalinowski", "RepMcClintock",
            "RepOHalleran", "TomReedCongress", "RepCardenas", "RepTrentKelly", "RepBalderson", "TulsiPress", "RepValDemings", "RepVanTaylor", "VernBuchanan", "RepEscobar",
            "RepGonzalez", "RepHartzler", "virginiafoxx", "WarrenDavidson", "WillHurd", "RepTimmons", "RepTorresSmall", "RepYvetteClarke", "RepZoeLofgren"]
start = datetime(2020, 5, 26, 0, 0, 0, 0, tzinfo=timezone.utc)
end = datetime(2020, 6, 10, 0, 0, 0, 0, tzinfo=timezone.utc)
tweets = []
for account in accounts:
  query = f"from: {account}"
  for c in twarc_client.search_all(
    query,
    start_time=start,
    end_time=end):
    tweets.append(c)

# converting the JSON entries to a pandas DataFrame
df1 = pd.json_normalize(tweets, record_path=['data'])
df1 = df1.sort_values(by="created_at", ascending = True)
print(df1)

# creating a pandas DataFrame of Tweets that mention "George" "Floyd" "protest"
df1_floyd = df1[df1['text'].str.contains('george|floyd|protest', case=False)]
df1_floyd = df1_floyd.sort_values(by="created_at", ascending = True)
print(df1_floyd)

# (2) for just the Democrats
accounts = ["SenDougJones", "SenatorSinema", "SenFeinstein", "VP", "SenatorBennet", "SenBlumenthal", "ChrisMurphyCT", "SenatorCarper", "ChrisCoons",
            "maziehirono", "SenBrianSchatz", "SenDuckworth", "SenatorDurbin", "SenMarkey", "SenWarren", "SenatorCardin", "ChrisVanHollen", "SenGaryPeters", "SenStabenow",
            "SenAmyKlobuchar", "SenTinaSmith", "SenatorTester", "SenatorHassan", "SenatorShaheen", "SenBooker", "SenatorMenendez", "MartinHeinrich", "SenatorTomUdall", "SenCortezMasto",
            "SenJackyRosen", "gillibrandny", "SenSchumer", "SenSherrodBrown", "SenJeffMerkley", "RonWyden", "SenBobCasey", "SenJackReed", "SenWhitehouse", "timkaine",
            "MarkWarner", "SenatorLeahy", "SenatorCantwell", "PattyMurray", "SenatorBaldwin", "Sen_JoeManchin",
            "RepFinkenauer", "RepSpanberger", "RepAdamSchiff", "RepAdamSmith", "RepEspaillat", "RepAlGreen", "AlLawsonJr", "RepLowenthal", "AlbioSiresNJ", "RepAOC",
            "RepAdams", "RepBera", "RepAndreCarson", "RepAndyKimNJ", "RepAndyLevin", "RepAngieCraig", "RepKirkpatrick", "RepAnnieKuster", "RepAnnaEshoo", "RepBrindisi",
            "OAGMaryland", "repdelgado", "RepPressley", "RepBarbaraLee", "BenMcAdamsUT", "SenatorLujan", "BennieGThompson", "BettyMcCollum04", "RepBillFoster",
            "USRepKeating", "BillPascrell", "BobbyLRush", "BobbyScott", "RepBonnie", "RepSchneider", "BradSherman", "RepLawrence", "CongBoyle",
            "RepBrianHiggins", "RepMaloney", "RepRichmond", "CharlieCrist", "ChelliePingree", "RepCheri", "RepChrisPappas", "RepHoulahan", "Axne4Congress", "RepColinAllred",
            "ConorLambPA", "RepDanKildee", "RepLipinski", "RepDannyDavis", "RepDarrenSoto", "daveloebsack", "RepCicilline", "RepDavidScott", "RepDavidTrone", "RepDeanPhillips",
            "RepDebHaaland", "RepDebDingell", "RepDMP", "RepDWStweets", "LtGovDennyHeck", "RepDerekKilmer", "RepDianaDeGette", "RepDinaTitus", "RepDonBeyer", "Donald_McEachin",
            "DonaldNorcross", "RepDonaldPayne", "DonnaShalala", "DorisMatsui", "Call_Me_Dutch", "RepDwightEvans", "repblumenauer", "RepEdCase", "RepPerlmutter", "RepEBJ",
            "ElaineLuriaVA", "EleanorNorton", "RepEliotEngel", "RepSlotkin", "repcleaver", "RepSwalwell", "RepFilemonVela", "FrankPallone", "RepWilson",
            "GKButterfield", "GerryConnolly", "RepGilCisneros", "RepGraceMeng", "gracenapolitano", "RepGregStanton", "RepGregoryMeeks", "RepGwenMoore", "RepJeffries", "RepHaleyStevens",
            "RepHankJohnson", "RepHarley", "RepCuellar", "Ilhan", "RepSpeier", "RepJahanaHayes", "JimLangevin", "RepRaskin", "janschakowsky", "RepGolden",
            "RepHuffman", "RepJasonCrow", "RepWexton", "RepJerryNadler", "RepMcNerney", "RepChuyGarcia", "RepJamesClyburn", "jimcoopertn", "RepJimCosta", "jahimes",
            "RepMcGovern", "RepJimmyGomez", "RepJimmyPanetta", "JoaquinCastrotx", "RepJoeCourtney", "RepCunningham", "RepJoeNeguse", "RepJohnLarson", "RepGaramendi", "repjohnlewis",
            "RepSarbanes", "JohnYarmuth", "RepJoseSerrano", "RepJoeMorelle", "joekennedy", "RepJoshG", "RepJoshHarder", "RepBeatty", "RepJuanVargas",
            "RepJudyChu", "RepBrownley", "RepKarenBass", "WhipKClark", "RepKathleenRice", "USRepKCastor", "RepKatiePorter", "HornForCongress", "RepKimSchrier", "RepSchrader",
            "LacyClayMO1", "RepUnderwood", "RepLindaSanchez", "RepLBR", "RepFletcher", "RepLloydDoggett", "RepLoisFrankel", "RepLoriTrahan", "RepLouCorrea", "RepRoybalAllard",
            "RepLucyMcBath", "RepDean", "RepVeasey", "RepMarciaFudge", "RepMarcyKaptur", "RepDeSaulnier", "RepMarkPocan", "RepMarkTakano", "RepMGS", "RepCartwright",
            "RepMaxRose", "RepMaxineWaters", "USRepMikeDoyle", "RepMikeLevin", "RepMikeQuigley", "RepThompson", "RepSherrill", "SpeakerPelosi", "RepBarragan",
            "NitaLowey", "NormaJTorres", "NydiaVelazquez", "RepPaulTonko", "RepPeteAguilar", "RepPeterDeFazio", "PeterWelch", "RepJayapal", "CongressmanRaja", "RepRashida",
            "RepRaulRuizMD", "RepRaulGrijalva", "RepRichardNeal", "RepRickLarsen", "RepRoKhanna", "RepRobinKelly", "RepRonKind", "rosadelauro", "RepRubenGallego", "RepCarbajal",
            "SanfordBishop", "RepScottPeters", "RepCasten", "RepSeanMaloney", "sethmoulton", "RepDavids", "JacksonLeeTX18", "StaceyPlaskett", "RepStenyHoyer", "RepStephMurphy",
            "RepStephenLynch", "RepCohen", "RepHorsford", "RepSusanWild", "RepSusieLee", "RepDelBene", "RepBonamici", "RepSylviaGarcia", "RepTedDeutch", "RepTedLieu",
            "RepTerriSewell", "RepTomSuozzi", "RepTimRyan", "RepTjCox", "RepMalinowski", "RepOHalleran", "RepCardenas", "TulsiPress", "RepValDemings", "RepEscobar",
            "RepGonzalez", "RepTorresSmall", "RepYvetteClarke", "RepZoeLofgren"]
start = datetime(2020, 5, 26, 0, 0, 0, 0, tzinfo=timezone.utc)
end = datetime(2020, 6, 10, 0, 0, 0, 0, tzinfo=timezone.utc)
tweets = []
for account in accounts:
  query = f"from: {account}"
  for c in twarc_client.search_all(
    query,
    start_time=start,
    end_time=end):
    tweets.append(c)

# converting the JSON entries to a pandas DataFrame
df2 = pd.json_normalize(tweets, record_path=['data'])
df2 = df2.sort_values(by="created_at", ascending = True)
print(df2)

# creating a pandas DataFrame of Tweets that mention "George" "Floyd" "protest"
df2_floyd = df2[df2['text'].str.contains('george|floyd|protest', case=False)]
df2_floyd = df2_floyd.sort_values(by="created_at", ascending = True)
print(df2_floyd)

# (3) for just the Republicans
accounts = ["lisamurkowski", "SenDanSullivan", "SenShelby", "JohnBoozman", "SenTomCotton", "MarthaMcSallyAZ", "SenCoryGardner", "marcorubio", "SenRickScott", "KLoeffler", "sendavidperdue",
            "SenJoniErnst", "ChuckGrassley", "MikeCrapo", "SenatorRisch", "SenatorBraun", "SenToddYoung", "JerryMoran", "SenPatRoberts", "LeaderMcConnell", "RandPaul", "SenBillCassidy", "SenJohnKennedy",
            "SenatorCollins", "RoyBlunt", "SenHawleyPress", "SenHydeSmith", "SenatorWicker", "SteveDaines", "SenatorBurr", "SenThomTillis", "SenKevinCramer", "SenJohnHoeven", "SenatorFischer", "SenSasse",
            "senrobportman", "JimInhofe", "SenatorLankford", "SenToomey", "LindseyGrahamSC", "SenatorTimScott", "SenatorRounds", "SenJohnThune", "SenAlexander", "MarshaBlackburn", "JohnCornyn", "SenTedCruz", "SenMikeLee", "SenatorRomney",
            "SenRonJohnson", "SenCapito", "SenJohnBarrasso", "SenatorEnzi",
            "RepKinzinger", "RepAdrianSmith", "RepAlexMooney", "RepAmata", "RepAndyBarr", "RepAndyBiggsAZ", "RepAndyHarrisMD", "RepAnnWagner",
            "AustinScottGA08", "RepLoudermilk", "RepBenCline", "RepHuizenga", "RepBillJohnson", "CongBillPosey", "auctnr1", "RepBlaine", "boblatta",
            "RepBradWenstrup", "RepByrne", "RepGuthrie", "RepBrianBabin", "RepBrianFitz",
            "RepBrianMast", "RepWesterman", "RepBryanSteil", "RepBuddyCarter", "RepCarolMiller", "CathyMcMorris", "RepChipRoy", "RepChrisStewart", "RepChuck", "RepClayHiggins",
            "RepDanBishop", "RepDanCrenshaw", "RepFredKeller", "RepGregMurphy", "RepMeuser", "RepNewhouse", "RepWebster", "RepLaHood", "RepDaveJoyce", "RepDavidKustoff", "RepMcKinley", "RepDavidRouzer", "RepDavid",
            "RepDLesko", "RepRiggleman", "RepDevinNunes", "RepDonBacon", "repdonyoung", "RepDougCollins", "RepLaMalfa", "RepDLamborn", "RepDrewFerguson", "RepDustyJohnson",
            "RepStefanik", "RepRooney", "RepFrankLucas", "RepFredUpton", "RepFrenchHill", "RepGarretGraves", "USRepGaryPalmer", "RepHolding", "RepGrothman", "CongressmanGT",
            "GregForMontana", "RepGregPence", "RepGregSteube", "repgregwalden", "RepGusBilirakis", "GReschenthaler", "RepHalRogers", "RepJackBergman", "RepWalorski", "HerreraBeutler",
            "RepJasonSmith", "RepJeffDuncan", "JeffFortenberry", "RepJenniffer", "RepJimBaird", "RepJimBanks", "RepHagedorn", "Jim_Jordan",
            "RepArrington", "CongressmanHice", "RepJoeWilson", "JudgeCarter", "RepJohnCurtis", "RepJohnJoyce", "RepJohnKatko", "RepMoolenaar", "JohnRatcliffe", "RepJohnRose",
            "RepRutherfordFL", "RepMikeGarcia", "RepKayGranger", "RepArmstrongND", "RepKenBuck", "KenCalvert", "RepKenMarchant", "RepKevinBrady", "repkevinhern", "kevinomccarthy",
            "Lancegooden", "RepLarryBucshon", "leezeldin", "RepLizCheney", "RepSmucker", "replouiegohmert", "MacTXPress", "MarioDB", "MarkAmodeiNV2", "RepMarkGreen",
            "RepMarkWalker", "SenMullin", "MarthaRobyAL", "RepMattGaetz", "michaelcburgess", "RepCloudTX", "RepMichaelGuest", "RepMcCaul", "RepWaltzPress", "RepBost",
            "ConawayTX11", "RepGallagher", "RepMikeJohnson", "MikeKellyPA", "RepMikeRogersAL", "CongMikeSimpson", "RepMikeTurner", "RepMoBrooks", "RepMGriffith", "DrNealDunnFL2",
            "PatrickMcHenry", "ColPaulCookRet", "RepGosar", "RepPaulMitchell", "RepPeteOlson", "RepPeteStauber", "RepPeteKing", "DrPhilRoe", "RepAbraham", "RepRalphNorman",
            "TXRandy14", "RepRichHudson", "RepRickCrawford", "RepRickAllen", "RobWittman", "RepRobWoodall", "Robert_Aderholt", "RodneyDavis", "RogerMarshallMD", "RepRWilliams",
            "RepRonEstes", "RepRonWright", "RepRossSpano", "RepRussFulcher", "RepSamGraves", "DesJarlaisTN04", "RepScottPerry", "RepTipton", "RepTiffany", "RepSteveChabot",
            "SteveKingIA", "SteveScalise", "RepSteveStivers", "rep_stevewomack", "CongPalazzo", "SusanWBrooks", "SenTedBuddNC", "RepTedYoho", "RepThomasMassie",
            "RepTimBurchett", "RepWalberg", "TomColeOK04", "GOPMajorityWhip", "RepTomGraves", "RepMcClintock", "TomReedCongress", "RepTrentKelly", "RepBalderson", "RepVanTaylor",
            "VernBuchanan", "RepHartzler", "virginiafoxx", "WarrenDavidson", "WillHurd", "RepTimmons"]
start = datetime(2020, 5, 26, 0, 0, 0, 0, tzinfo=timezone.utc)
end = datetime(2020, 6, 10, 0, 0, 0, 0, tzinfo=timezone.utc)
tweets = []
for account in accounts:
  query = f"from: {account}"
  for c in twarc_client.search_all(
    query,
    start_time=start,
    end_time=end):
    tweets.append(c)

# converting the JSON entries to a pandas DataFrame
df3 = pd.json_normalize(tweets, record_path=['data'])
df3 = df3.sort_values(by="created_at", ascending = True)
print(df3)

# creating a pandas DataFrame of Tweets that mention "George" "Floyd" "protest"
df3_floyd = df3[df3['text'].str.contains('george|floyd|protest', case=False)]
df3_floyd = df3_floyd.sort_values(by="created_at", ascending = True)
print(df3_floyd)

# saving dataframes as csv file
df1.to_excel('all_2weeks.xlsx')
df1_floyd.to_excel('all_floyd_2weeks.xlsx')
df2.to_excel('dem_2weeks.xlsx')
df2_floyd.to_excel('dem_floyd_2weeks.xlsx')
df3.to_excel('rep_2weeks.xlsx')
df3_floyd.to_excel('rep_floyd_2weeks.xlsx')

# Pie chart for all Tweet counts in the first 2 weeks by party
y = np.array([14877, 186, 8004])
party = ["Democrats","Independents","Republicans"]
patches, texts, pcts = plt.pie(y, labels = party, autopct="%.0f%%", colors=["#4374B3","green","#A62C2B"])
plt.setp(pcts, color='white', fontweight='bold')
plt.show()

# *All Floyd-related Tweet counts for all members in the first 2 weeks*
df1_floyd_count = pd.read_excel("all_floyd_2weeks_clean.xlsx")
df1_floyd_count['datetime'] = pd.to_datetime(df1_floyd_count['created_at'], format = '%Y-%m-%d')
df1_floyd_count['date'] = pd.to_datetime(df1_floyd_count['datetime']).dt.date
count_all_floyd_2weeks = df1_floyd_count.groupby(by='date', as_index=False).count()
count_all_floyd_2weeks = pd.DataFrame(count_all_floyd_2weeks, columns=['date','text'])
count_all_floyd_2weeks

# *Floyd-related Tweet counts for just the Democrats*
df2_floyd_count = pd.read_excel("dem_floyd_2weeks_clean.xlsx")
df2_floyd_count['datetime'] = pd.to_datetime(df2_floyd_count['created_at'], format = '%Y-%m-%d')
df2_floyd_count['date'] = pd.to_datetime(df2_floyd_count['datetime']).dt.date
count_dem_floyd_2weeks = df2_floyd_count.groupby(by='date', as_index=False).count()
count_dem_floyd_2weeks = pd.DataFrame(count_dem_floyd_2weeks, columns=['date','text'])
count_dem_floyd_2weeks

# *Floyd-related Tweet counts for just the Republicans*
df3_floyd_count = pd.read_excel("rep_floyd_2weeks_clean.xlsx")
df3_floyd_count['datetime'] = pd.to_datetime(df3_floyd_count['created_at'], format = '%Y-%m-%d')
df3_floyd_count['date'] = pd.to_datetime(df3_floyd_count['datetime']).dt.date
count_rep_floyd_2weeks = df3_floyd_count.groupby(by='date', as_index=False).count()
count_rep_floyd_2weeks = pd.DataFrame(count_rep_floyd_2weeks, columns=['date','text'])
count_rep_floyd_2weeks

# plotting: *Floyd* Tweet Counts for House members and Senators in the first 2 weeks*
figx, axes = plt.subplots(1, 1, figsize=(10, 6))
axes.plot(count_all_floyd_2weeks["date"], count_all_floyd_2weeks["text"], label = "All", color = "green", linewidth = 3)
axes.plot(count_dem_floyd_2weeks["date"], count_dem_floyd_2weeks["text"], label = "Democrats", color = "blue", linewidth = 3)
axes.plot(count_rep_floyd_2weeks["date"], count_rep_floyd_2weeks["text"], label = "Republicans", color = "red", linewidth = 3)
axes.set_title("Floyd-related Tweets from House members and Senators")
axes.legend(frameon=False, fontsize=12)
plt.ylabel("Count")
axes.set_xticklabels(["May 27","May 29","May 31","Jun 1","Jun 3","Jun 5","Jun 7","Jun 9"], fontsize=10, rotation = 45)

# saving plot into image file
import matplotlib.pyplot as plt
plt.savefig('Tweet counts from House members and Senators.png')